apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-viz
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"  # Deploy after linkerd control plane
spec:
  project: default

  source:
    chart: linkerd-viz
    repoURL: https://helm.linkerd.io/stable
    targetRevision: 30.12.11
    helm:
      valuesObject:
        # Prometheus integration (use existing Prometheus)
        prometheusUrl: http://prometheus-stack-kube-prom-prometheus.monitoring.svc.cluster.local:9090

        # Dashboard configuration
        dashboard:
          replicas: 1

        # Grafana integration (use existing Grafana)
        grafana:
          enabled: false
          externalUrl: http://prometheus-stack-grafana.monitoring.svc.cluster.local

        # Disable embedded Prometheus
        prometheus:
          enabled: false

        # Tap configuration
        tap:
          replicas: 1

        # Metrics API
        metricsAPI:
          replicas: 1

  destination:
    server: https://kubernetes.default.svc
    namespace: linkerd-viz

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
