apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: smtp-relay
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/softwareengineerva/eks.git
    targetRevision: HEAD
    path: k8s-manifests/smtp-relay/base
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  # Sync Policy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false  # argocd namespace already exists
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m

  # Health assessment
  revisionHistoryLimit: 5
