apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
type: Opaque
stringData:
  # Slack channel email for notifications
  slack-channel-email: jian-private-aaaaq6nbninfp6bphtpr3pwl7m@sap.org.slack.com

  # Slack webhook token (optional, if you want to use webhooks instead)
  # Get your Slack webhook URL from: https://api.slack.com/messaging/webhooks
  # Format: https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXX
  # slack-token: https://hooks.slack.com/services/YOUR_WORKSPACE_ID/YOUR_CHANNEL_ID/YOUR_SECRET_TOKEN
