apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: postgres-secrets
  namespace: postgres
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "concur-test-postgres-credentials"
        objectType: "secretsmanager"
        jmesPath:
          - path: username
            objectAlias: username
          - path: password
            objectAlias: password
          - path: database
            objectAlias: database
  secretObjects:
    - secretName: postgres-secret
      type: Opaque
      data:
        - objectName: username
          key: username
        - objectName: password
          key: password
        - objectName: database
          key: database
