apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-sa
  namespace: postgres
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::865286230013:role/concur-test-postgres-secrets-csi-role
